sudo: false

branches:
  only:
    - 6.x
    - master
    - split_feature_targets

language: java
install: ./gradlew b
script: ./gradlew integrationTest
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.gradle
